// Generated by CoffeeScript 1.12.2
var Col, Row;

Col = (function() {

  /*
    size between 1 .. 12
   */
  function Col(title, size, content) {
    this.title = title;
    this.size = size;
    this.content = content;
    this.id = md5(this.title);
  }

  Col.prototype.isTableCol = function() {
    return typeof this.content !== "object";
  };

  Col.prototype.getMinHeight = function() {
    if (this.isTableCol()) {
      return "50px";
    } else {
      return "300px";
    }
  };

  Col.prototype.render = function() {
    if (!this.isTableCol()) {
      return Drawer.draw(this.id, this.content, this.title);
    } else {
      return Drawer.drawTable(this.id, this.content);
    }
  };

  return Col;

})();

Row = (function() {
  function Row(title, iconClass, comments) {
    this.title = title;
    this.iconClass = iconClass;
    this.comments = comments;
    this.cols = [];
  }

  Row.prototype.append = function(col) {
    this.cols.push(col);
    return this;
  };

  Row.prototype.toHtml = function() {
    var col, commentsHtml, i, len, ref, rowHtml;
    commentsHtml = "";
    if (this.comments !== void 0) {
      commentsHtml = "<div class='col-md-12'><blockquote class='blockquote'><p>" + this.comments + "</p></blockquote></div>";
    }
    rowHtml = "";
    ref = this.cols;
    for (i = 0, len = ref.length; i < len; i++) {
      col = ref[i];
      rowHtml = rowHtml + ("<div class='col-md-" + col.size + "'><h4>- " + col.title + "</h4><div id='" + col.id + "' style='min-height: " + (col.getMinHeight()) + "'></div></div>");
    }
    return "<div class=\"row\">\n  <div><h2><i class=\"" + this.iconClass + "\" aria-hidden=\"true\" style=\"color:#696969;\"></i> " + this.title + " </h2></div>\n  " + commentsHtml + "\n  " + rowHtml + "\n</div>\n<div class='row'><hr/></div>";
  };

  Row.prototype.render = function() {
    var col, i, len, ref, results;
    ref = this.cols;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      col = ref[i];
      results.push(col.render());
    }
    return results;
  };

  return Row;

})();
